package com.fcc.exception;

public enum ApiErrorCode {
	ACCESS_DENIED, MISSING_QUERY_PARAM, INCORRECT_CREDENTIALS, INVALID_INPUT, RESOURCE_NOT_FOUND, USER_EMAIL_NOT_VERIFIED, RESOURCE_INACTIVE,
	NO_ACTIVE_SUBSCRIPTION, EMAIL_ALREADY_EXIST, TRIAL_EXPIRED, CLASS_ALREADY_EXIST, NO_SLOTS_EXISTS, COUPON_EXPIRED, INVALID_COUPON, INVALID_PASSWORD,INTERNAL_ERROR
}
